app/routes.py
from flask import Flask, Blueprint, render_template, request, redirect, url_for, Response
import io
import base64
from .models import Ticket, Product, ProductTicket, PaymentType, Description
from . import db
from datetime import datetime
from matplotlib.figure import Figure
from matplotlib.dates import DateFormatter
from matplotlib.ticker import MultipleLocator
import json

bp = Blueprint('main', __name__)

@bp.route('/add_expense', methods=['GET', 'POST'])
def add_expense():
    if request.method == 'POST':
        # Obtener datos del formulario
        description_existing_id = request.form.get('description_existing')
        description_new = request.form.get('description_new').strip()

        # Determinar la descripción del ticket
        if description_existing_id:
            description = Description.query.get(description_existing_id)
        elif description_new:
            description = Description.query.filter_by(name=description_new).first()
            if not description:
                description = Description(name=description_new)
                db.session.add(description)
                db.session.commit()
        else:
            return "Debes elegir o agregar una descripción."

        total_amount = float(request.form['amount'])
        date = datetime.strptime(request.form['date'], '%Y-%m-%d')
        local = request.form['local']
        payment_type_id = request.form['payment_type']

        # Crear el ticket
        ticket = Ticket(description=description, total_amount=total_amount, date=date, local=local, payment_type_id=payment_type_id)
        db.session.add(ticket)
        db.session.commit()

        # Procesar y asociar productos con el ticket
        products_data = request.form.get('products')
        if products_data:
            products = json.loads(products_data)
            for product in products:
                product_name = product['name']
                product_price = product['price']
                product_quantity = product['quantity']

                # Comprobar si el producto ya existe, si no, crearlo
                existing_product = Product.query.filter_by(name=product_name).first()
                if not existing_product:
                    existing_product = Product(name=product_name)
                    db.session.add(existing_product)
                    db.session.commit()

                # Crear una entrada en ProductTicket para cada compra
                product_ticket_entry = ProductTicket(
                    product_id=existing_product.id,
                    ticket_id=ticket.id,
                    quantity=product_quantity,
                    price=product_price,
                    date=date
                )
                db.session.add(product_ticket_entry)

        db.session.commit()
        return redirect(url_for('main.index'))

    payment_types = PaymentType.query.all()
    descriptions = Description.query.all()
    return render_template('add_expense.html', payment_types=payment_types, descriptions=descriptions)

@bp.route('/product_history/<int:product_id>')
def product_history(product_id):
    # Obtener el producto y el historial de compras completo
    product = Product.query.get_or_404(product_id)
    price_history = ProductTicket.query.filter_by(product_id=product_id).order_by(ProductTicket.date.desc()).all()

    # Filtrar el historial para mostrar solo cambios de precio
    filtered_history = []
    
    for i in range(len(price_history)):
        current_record = price_history[i]
        next_record = price_history[i+1] if i+1 < len(price_history) else None

        # Solo añadimos el registro si es el último con un precio constante antes de un cambio, o si es el último registro
        if (next_record and current_record.price != next_record.price) or not next_record:
            filtered_history.append(current_record)

    # Calcular el precio más bajo y el más alto
    lowest_price_record = ProductTicket.query.filter_by(product_id=product_id).order_by(ProductTicket.price.asc()).first()
    highest_price_record = ProductTicket.query.filter_by(product_id=product_id).order_by(ProductTicket.price.desc()).first()
    
    # Definir last_ticket_id como el ticket del último elemento en filtered_history
    last_ticket_id = filtered_history[-1].ticket_id if filtered_history else None

    # Preparar datos para el gráfico, usando solo las fechas y precios de filtered_history
    dates = [record.date for record in filtered_history]
    prices = [record.price for record in filtered_history]

    fig = Figure()
    ax = fig.subplots()
    ax.plot(dates, prices, marker='o', color='b')    
    #ax.set_xlabel('Fecha')
    #ax.set_ylabel('Precio (€)')
    ax.grid(True)

    # Formato de fecha personalizado en el eje X y establecer ticks específicos
    date_format = DateFormatter("%d/%m/%y")
    ax.xaxis.set_major_formatter(date_format)
    ax.set_xticks(dates)  # Solo mostrar fechas con cambios de precio
    fig.autofmt_xdate()  # Rotar las fechas para mejor visualización

    # Ajustar el eje Y para incrementos de 0.05 euros
    ax.yaxis.set_major_locator(MultipleLocator(0.05))

    # Convertir gráfico a imagen para mostrar en el HTML
    img = io.BytesIO()
    fig.savefig(img, format='png')
    img.seek(0)
    plot_url = base64.b64encode(img.getvalue()).decode()

    return render_template(
        'product_history.html',
        product=product,
        price_history=filtered_history,
        lowest_price_record=lowest_price_record,
        highest_price_record=highest_price_record,
        last_ticket_id=last_ticket_id,
        plot_url=plot_url
    )


@bp.route('/')
def index():
    return render_template('index.html')

@bp.route('/view_tickets')
def view_tickets():
    # Número de tickets a mostrar
    ticket_count = 10
    # Consultar los últimos tickets
    tickets = Ticket.query.order_by(Ticket.date.desc()).limit(ticket_count).all()
    return render_template('view_tickets.html', tickets=tickets)


@bp.route('/ticket_detail/<int:ticket_id>')
def ticket_detail(ticket_id):
    # Consulta el ticket y usa la tabla intermedia ProductTicket para obtener los productos
    ticket = Ticket.query.get_or_404(ticket_id)
    product_tickets = ProductTicket.query.filter_by(ticket_id=ticket_id).all()
    return render_template('ticket_detail.html', ticket=ticket, product_tickets=product_tickets)

app/templates/add_expense.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Añadir Gasto</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
</head>
<body>
    <div class="container">
        <!-- Sección del Formulario -->
        <div class="form-section">
            <h1>Añadir un nuevo gasto</h1>
            <form id="expense-form" action="/add_expense" method="POST">
                <label for="description">Descripción:</label>
                <select id="description" name="description_existing">
                    <option value="">Selecciona una descripción existente...</option>
                    {% for desc in descriptions %}
                        <option value="{{ desc.id }}">{{ desc.name }}</option>
                    {% endfor %}
                </select>
                <input type="text" id="description_new" name="description_new" placeholder="O añade una nueva descripción">

                <label for="amount">Cantidad Total:</label>
                <input type="number" id="amount" name="amount" step="0.01" required>

                <label for="date">Fecha:</label>
                <input type="date" id="date" name="date" required>

                <label for="local">Local:</label>
                <input type="text" id="local" name="local" required>

                <label for="payment_type">Tipo de Pago:</label>
                <select id="payment_type" name="payment_type" required>
                    {% for payment in payment_types %}
                        <option value="{{ payment.id }}">{{ payment.name }}</option>
                    {% endfor %}
                </select>

                <!-- Entrada de Producto -->
                <div id="product_input">
                    <h3>Nuevo Producto</h3>
                    <label>Producto:</label>
                    <input type="text" id="product_name">
                    <label>Precio:</label>
                    <input type="number" id="product_price" step="0.01">
                    <label>Cantidad:</label>
                    <input type="number" id="product_quantity" step="0.01">
                </div>
                <button type="button" onclick="addProduct()">Añadir Producto</button><br><br>
                
                <!-- Campo oculto para enviar los productos -->
                <input type="hidden" id="products" name="products">

                <button type="submit" onclick="prepareForm()">Guardar ticket</button>
            </form>
        </div>

        <!-- Sección de Vista Previa del Ticket -->
        <div class="ticket-preview">
            <h2>Vista Previa del Ticket</h2>
            <div id="product_list" class="product-list">
                <!-- Los productos añadidos se mostrarán aquí -->
            </div>
        </div>
    </div>

    <script>
        const productList = document.getElementById("product_list");
        let products = [];

        // Función para añadir un producto al listado y actualizar la vista previa
        function addProduct() {
            const name = document.getElementById("product_name").value;
            const price = parseFloat(document.getElementById("product_price").value);
            const quantity = parseFloat(document.getElementById("product_quantity").value);

            if (!name || isNaN(price) || isNaN(quantity)) {
                alert("Por favor, complete todos los campos del producto.");
                return;
            }

            // Añadir el producto al array de productos
            const product = { name, price, quantity };
            products.push(product);

            // Actualizar la vista previa del ticket
            renderProductList();

            // Limpiar los campos de entrada
            document.getElementById("product_name").value = '';
            document.getElementById("product_price").value = '';
            document.getElementById("product_quantity").value = '';
        }

        // Función para renderizar el listado de productos en la vista previa
        function renderProductList() {
            productList.innerHTML = '';

            products.forEach((product, index) => {
                const productItem = document.createElement("div");
                productItem.classList.add("product-item");
                productItem.innerHTML = `
                    <span>${product.name} - Precio: €${product.price.toFixed(2)} - Cantidad: ${product.quantity}</span>
                    <button onclick="removeProduct(${index})">Eliminar</button>
                `;
                productList.appendChild(productItem);
            });
        }

        // Función para eliminar un producto de la lista
        function removeProduct(index) {
            products.splice(index, 1);
            renderProductList();
        }

        // Función para preparar el formulario y enviar los productos junto con los datos del ticket
        function prepareForm() {
            document.getElementById("products").value = JSON.stringify(products);
        }
    </script>
</body>
</html>

app/templates/index.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Control de Gastos App</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
</head>
<body>
    <div class="welcome-container">
        <h1>Control de Gastos</h1>
        <a href="{{ url_for('main.add_expense') }}" class="add-expense-link">Añadir Gasto</a>
		<a href="{{ url_for('main.view_tickets') }}" class="view-tickets-link">Ver Últimos Tickets</a>
    </div>
</body>
</html>

app/templates/product_history.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Historial de Precios</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <script>
        // Función para mostrar y ocultar el gráfico
        function toggleGraph() {
            var graphDiv = document.getElementById("price-graph");
            var button = document.getElementById("toggle-graph-btn");
            if (graphDiv.style.display === "none") {
                graphDiv.style.display = "block";
                button.textContent = "Ocultar Gráfico";
            } else {
                graphDiv.style.display = "none";
                button.textContent = "Mostrar Gráfico";
            }
        }
    </script>
</head>
<body>
    <div class="welcome-container">
        <h1>{{ product.name }}</h1>

        <div class="price-info">
            {% if lowest_price_record %}
                <p><strong>Precio más bajo:</strong> <span class="lowest-price">€{{ lowest_price_record.price }}</span> ({{ lowest_price_record.date.strftime('%Y-%m-%d') }})</p>
            {% endif %}
            {% if highest_price_record %}
                <p><strong>Precio más alto:</strong> <span class="highest-price">€{{ highest_price_record.price }}</span> ({{ highest_price_record.date.strftime('%Y-%m-%d') }})</p>
            {% endif %}
        </div>

        {% if price_history %}
            <table class="ticket-table">
                <thead>
                    <tr>
                        <th>Fecha</th>
                        <th>Precio</th>
                        <th>Ticket ID</th>
                    </tr>
                </thead>
                <tbody>
                    {% for record in price_history %}
                        <tr>
                            <td>{{ record.date.strftime('%Y-%m-%d') }}</td>
                            <td>€{{ record.price | round(2) }}</td>
                            <td>{{ record.ticket_id }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% else %}
            <p>No hay historial de precios disponible para este producto.</p>
        {% endif %}
        
        <!-- Botones para volver al índice y al último ticket -->
        <div class="button-container">
            <!-- Botón para mostrar/ocultar el gráfico -->
            <button id="toggle-graph-btn" onclick="toggleGraph()" class="view-tickets-link">Mostrar Gráfico</button>
            <a href="{{ url_for('main.index') }}" class="btn">Volver al Índice</a>
            {% if last_ticket_id %}
                <a href="{{ url_for('main.ticket_detail', ticket_id=last_ticket_id) }}" class="btn">Volver al Último Ticket</a>
            {% endif %}                    
        </div>

        
        <!-- Div que contiene el gráfico, inicialmente escondido -->
        <div id="price-graph" style="display: none;">
            {% if plot_url %}            
                <img src="data:image/png;base64,{{ plot_url }}" alt="Gráfico de historial de precios">
            {% endif %}
        </div>

        
    </div>
</body>
</html>

app/templates/ticket_detail.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Detalle del Ticket</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
</head>
<body>
    <div class="welcome-container">
        <h1>Detalle del Ticket</h1>

        <h2>Descripción: {{ ticket.description.name }}</h2>
        <p><strong>Fecha:</strong> {{ ticket.date.strftime('%Y-%m-%d') }}</p>
        <p><strong>Cantidad Total:</strong> €{{ ticket.total_amount }}</p>

        <h2>Productos</h2>
        {% if product_tickets %}
            <table class="ticket-table">
                <thead>
                    <tr>
                        <th>Nombre</th>
                        <th>Cantidad</th>
                        <th>Precio</th>
                        <th>Total</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in product_tickets %}
                        <tr>
                            {% if item.product %}
                                <td><a href="{{ url_for('main.product_history', product_id=item.product.id) }}"><strong>{{ item.product.name }}</strong></a></td>
                                <td>{{ item.quantity }}</td>
                                <td>€{{ item.price }}</td>
                                <td><strong>€{{ (item.price * item.quantity) | round(2) }}</strong></td>
                            {% else %}
                                <td colspan="4">Producto no encontrado</td>
                            {% endif %}
                        </tr>
                    {% endfor %}
                </tbody>                
            </table>
        {% else %}
            <p>No hay productos asociados a este ticket.</p>
        {% endif %}
        
        <a href="{{ url_for('main.view_tickets') }}" class="add-expense-link">Volver a Tickets</a>
    </div>
</body>
</html>

app/templates/view_tickets.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Últimos Tickets</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
</head>
<body>
    <div class="welcome-container">
        <h1>Últimos Tickets</h1>
        
        {% if tickets %}
            <table class="ticket-table">
                <thead>
                    <tr>
                        <th>Descripción</th>
                        <th>Fecha</th>
                        <th>Cantidad Total</th>
                    </tr>
                </thead>
                <tbody>
                    {% for ticket in tickets %}
                        <tr onclick="window.location='{{ url_for('main.ticket_detail', ticket_id=ticket.id) }}'" style="cursor: pointer;">
                            <td>{{ ticket.description.name }}</td>
                            <td>{{ ticket.date.strftime('%Y-%m-%d') }}</td>
                            <td>€{{ ticket.total_amount }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% else %}
            <p>No hay tickets disponibles.</p>
        {% endif %}
        
        <a href="{{ url_for('main.index') }}" class="add-expense-link">Volver al Inicio</a>
    </div>
</body>
</html>